### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by jpaugh** [tkellogg/comboEditable#1]
I can't get the [demo] to do anything a regular select would not do. I think this is supposed to allow editing values within the dropdown before submitting, but clicking/typing in the select does not cause that behavior. I've tried the demo in recent versions of Chrome and FF, and in IE11, with the same result.

On a related note, I'm not exactly sure how an "editable" combo should be different from a regular combo, but what I think it means sounds interesting. Perhaps a screenshot would help clarify?

[demo]: http://timkellogg.me/comboEditable/

**Comment by tkellogg** [comment]
This is from a long time ago, I completely forgot what this even does. There are probably better options available of whatever it does, but your welcome to fix it.
